Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,30 +1,65 @@
-name: AutomaticHost
+name: CI and CD Sphinx
+
 on:
   push:
-    branches: 
+    branches:
       - main
+      
 jobs:
   build:
     runs-on: ubuntu-latest
     container: siewyanhoh/sphinx-env:latest
+    
     steps:
-    - uses: actions/checkout@v2
-    - uses: actions/setup-node@v1
-      with:
-        node-version: '10.x'
-    - run: |
-        cd docsrc
-        make github
-    - run: |
-        git config --local user.email "siew.yan.hoh@github.com"
-        git config --local user.name "SiewYan"
-        git checkout --orphan gh-pages
-        git reset
-        git add docs/* -f
-        git mv docs/* ./ -k
-        git commit -m "Update hosted version"
-    - uses: ad-m/github-push-action@master
-      with:
-        github_token: ${{ secrets.MY_TOKEN }}
-        force: true
-        branch: gh-pages
+      - name: checkout repository
+        uses: actions/checkout@v2
+        
+      - name: build sphinx
+        run: |
+          cd docsrc
+          make github
+          
+      - name: store artifact output website
+        uses: actions/upload-artifact@v2
+        with:
+          name: Index HTML 
+          path: docs/
+      - name: store artifact pdf
+        uses: actions/upload-artifact@v2
+        with:
+          name: PDF documentation
+          path: docsrc/_build/rinoh/cms-gen.pdf
+          
+  # Publish built docs to gh-pages branch.
+  autohost:
+    runs-on: ubuntu-latest
+    needs: build
+    steps:
+      - name: commit and deploy new changes
+        run: | 
+          git clone https://github.com/SiewYan/cmsgen.github.io.git --branch gh-pages --single-branch gh-pages
+          cp -r docs/* gh-pages/
+          cd gh-pages
+          git config --local user.email "siew.yan.hoh@github.com"
+          git config --local user.name "SiewYan"
+          git add .
+          git commit -m "Update documentation" -a || true
+          # The above command will fail if no changes were present, so we ignore
+          # the return code.
+      - name: Push changes
+        uses: ad-m/github-push-action@master
+        with:
+          branch: gh-pages
+          directory: gh-pages
+          github_token: ${{ secrets.GITHUB_TOKEN }}
+          
+          
+          
+          
+          
+          
+          
+          
+          
+          
+  
